# Generated by Django 3.1.7 on 2021-04-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpgm', '0004_auto_20210413_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresshistory',
            old_name='customuser',
            new_name='added_by',
        ),
    ]
