# Generated by Django 3.1.7 on 2021-04-15 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginpgm', '0005_auto_20210415_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresshistory',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customuser'),
            preserve_default=False,
        ),
    ]
