# Generated by Django 3.1.7 on 2021-04-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpgm', '0007_auto_20210415_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresshistory',
            old_name='email',
            new_name='updated_by',
        ),
    ]
