# Generated by Django 3.1.7 on 2021-04-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpgm', '0009_auto_20210415_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresshistory',
            old_name='updated_by',
            new_name='addresshistory',
        ),
    ]
