# Generated by Django 3.1.7 on 2021-04-16 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginpgm', '0010_auto_20210416_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresshistory',
            name='addresshistory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='addresshistory',
            name='home_address',
            field=models.CharField(max_length=200, verbose_name='New Address'),
        ),
        migrations.AlterField(
            model_name='addresshistory',
            name='home_address_move_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Moved In'),
        ),
        migrations.AlterField(
            model_name='addresshistory',
            name='home_address_move_out_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date Moved Out'),
        ),
    ]
