# Generated by Django 3.1.7 on 2021-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpgm', '0011_auto_20210417_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresshistory',
            name='home_address_move_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Moved Out'),
        ),
    ]
