# Generated by Django 3.1.7 on 2021-04-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpgm', '0012_auto_20210417_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresshistory',
            options={'ordering': ['addresshistory', 'home_address_move_date']},
        ),
    ]
