# Generated by Django 3.1.7 on 2021-04-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpgm', '0013_auto_20210422_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresshistory',
            options={'ordering': ['addresshistory_id', 'home_address_move_date']},
        ),
    ]
