# Generated by Django 3.1.7 on 2021-04-15 18:10

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0014_auto_20210330_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(error_messages={'unique': 'Email address already exists.'}, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Email address')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='username')),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('home_address', models.CharField(max_length=200)),
                ('national_insurance_number', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=100)),
                ('salary_initial', models.CharField(max_length=20, verbose_name='Starting salary')),
                ('bank_account_number', models.CharField(max_length=20, verbose_name='Account number')),
                ('work_eligibility', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth')),
                ('bank_sort_code', models.CharField(max_length=10, verbose_name='Sort Code')),
                ('emergency_contact_name', models.CharField(max_length=200, verbose_name='Name')),
                ('emergency_contact_number', models.CharField(max_length=20, verbose_name='Contact number')),
                ('emergency_contact_address', models.CharField(max_length=200, verbose_name='Address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Logged in date')),
                ('date_of_joining', models.DateField(default=django.utils.timezone.now, verbose_name='Date of joining')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('emergency_contact_relationship', models.CharField(max_length=150)),
                ('home_address_move_date', models.DateField(default=django.utils.timezone.now, verbose_name='Address Move Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
