# Generated by Django 3.1.7 on 2021-07-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='timehsheet_week_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
