# Generated by Django 3.1.7 on 2021-07-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_timesheet_timehsheet_week_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='timehsheet_week_id',
        ),
    ]
