# Generated by Django 3.1.7 on 2021-04-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210422_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='home_address_move_date',
            field=models.DateField(null=True, verbose_name='Address Move Date'),
        ),
    ]
