# Generated by Django 3.1.7 on 2021-07-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_timesheet_timehsheet_week_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='timehsheet_week_id',
            new_name='timesheet_week_id',
        ),
    ]
