# Generated by Django 3.1.7 on 2021-07-28 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210727_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetweek',
            name='week_date_format',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
