# Generated by Django 3.1.7 on 2021-04-23 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210422_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='weekdates',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
