# Generated by Django 3.1.7 on 2021-07-30 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_timesheetweek_week_date_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=100)),
                ('expense_net', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('expense_VAT', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('expense_gross', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('comments', models.CharField(max_length=150, null=True)),
                ('expense_date', models.DateField()),
                ('expense_update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Logged in date')),
                ('expense_attachment', models.ImageField(null=True, upload_to='')),
                ('userid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
