# Generated by Django 3.1.7 on 2021-07-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='comments',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('TRVL', 'Travel Expense'), ('TAXI', 'Taxi'), ('PARK', 'Parking'), ('CARM', 'Car Mileage'), ('POST', 'Postage'), ('PRNT', 'Print and Stationery'), ('BOOK', 'Books'), ('NEWS', 'News and Magazine'), ('SUBS', 'Subsistence'), ('HOME', 'Use of Home'), ('MEAL', 'Evening Meals'), ('HOTL', 'Hotels')], max_length=100),
        ),
    ]
