# Generated by Django 3.1.7 on 2021-04-26 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210426_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='work_eligibility',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='residence_permit_number',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='valid_from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='valid_to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
