# Generated by Django 3.1.7 on 2021-08-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210804_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='is_standard_VAT',
            field=models.BooleanField(default=True),
        ),
    ]
