# Generated by Django 3.1.7 on 2021-08-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210804_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='is_standard_VAT',
            field=models.CharField(max_length=5),
        ),
    ]
