# Generated by Django 3.1.7 on 2021-05-07 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_timesheet_total_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdates', models.CharField(max_length=40, verbose_name='Start Date')),
                ('total_hours', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('userid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
