# Generated by Django 3.1.7 on 2021-05-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_timesheetweek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheetweek',
            old_name='userid',
            new_name='user_id',
        ),
    ]
