# Generated by Django 3.1.7 on 2021-08-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210804_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
