# Generated by Django 3.1.7 on 2021-05-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210507_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='total_hours',
            field=models.IntegerField(blank=True),
        ),
    ]
