# Generated by Django 3.1.7 on 2021-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210512_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visa_type',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
