# Generated by Django 3.1.7 on 2021-05-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_customuser_visa_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('PG', 'Pending'), ('SUB', 'Submitted'), ('APPRVD', 'Approved'), ('SVD', 'Saved')], max_length=20),
        ),
    ]
