# Generated by Django 3.1.7 on 2021-05-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20210513_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='visa_type',
            field=models.CharField(choices=[('T1', 'Tier 1 (General) visa'), ('T2', 'Tier 1 (Exceptional Talent) visa'), ('T3', 'Tier 1 (Investor) visa'), ('T4', 'Tier 1 (Entrepreneur) visa'), ('T5', 'Highly Skilled Migrant Programme'), ('T6', 'Tier 2 (General) visa'), ('T7', 'Tier 2 (Minister of Religion) visa'), ('T8', 'Tier 2 (Sportsperson) visa'), ('T9', 'Tier 2 (Intra-Company Transfer) visa'), ('T10', 'Tier 5 (International Agreement) visa'), ('T11', 'Turkish Businessperson or Turkish Worker visa'), ('T12', 'Work Permit'), ('T13', 'Sole Representative of an Overseas Business visa'), ('T14', 'Representative of an Overseas Newspaper, News Agency or Broadcaster visa'), ('T15', 'Domestic Worker visa'), ('T16', 'Skilled Worker visa'), ('T17', 'Global Talent visa'), ('T18', 'Innovator visa'), ('T19', 'Family visa')], max_length=100),
        ),
    ]
