# Generated by Django 3.1.7 on 2021-05-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20210514_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='timesheetweek',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
