# Generated by Django 3.1.7 on 2021-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20210527_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='valid_from_date',
            field=models.DateField(null=True, verbose_name='Valid from date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='valid_to_date',
            field=models.DateField(null=True, verbose_name='Valid to date'),
        ),
    ]
